CREATE TABLE invoice (
    id           bigint                      NOT NULL,
    reference    character varying(255)      NOT NULL,
    value        bigint                      NOT NULL,
    employee_id  bigint                      NOT NULL,
    version      bigint                      NOT NULL,
    created_at   timestamp without time zone NOT NULL,
    updated_at   timestamp without time zone NOT NULL
);

ALTER TABLE ONLY invoice
    ADD CONSTRAINT invoice_pkey     PRIMARY KEY (id);

ALTER TABLE invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY invoice
    ADD CONSTRAINT fk_invoice_employee
    FOREIGN KEY (employee_id)
    REFERENCES employee(id);