spring:
  application:
    name: jpa-sample
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devcave_jpa_sample
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    ignore-missing-migrations: true
    out-of-order: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}